[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
]

[fmt]
int_types = "long"
line_length = 120  
bracket_spacing = true
multiline_func_header = "attributes_first"
contract_new_lines = true
override_spacing = true
tab_width = 4
number_underscore = "thousands"
quote_style = "double"
wrap_comments = true
